var tracery = require('tracery-grammar');
 
var grammar = tracery.createGrammar({
	"origin": [
		"#start#, #middle#, #end#.",
		"#start#, #middle#.",
		"#start#, #end#."
	],
	"anyadjective": [
		"#positiveadjective#",
		"#negativeadjective#",
		"#unbiasedadjective#"
	],
	"on": [
		"on the",
		"as we continued our",
		"upon our",
		"on the #order# night of our"
	],
	"start": [
		"It was #time# #on# #trip# when #aware# #feature#",
		"We passed the #symbols# near #feature#",
		"The #order# dream of #feature# came to #who#",
		"We found word of #feature# but not of #feature#",
		"We recruited #who# from the #proximity# #settlement#",
		"It was the #drive# of #who# that drove us on",
		"Our #order# path followed the migrating #color# #animals#",
		"The #trip# became a #state# #trip#",
		"Ahead #aware# a path of #material#",
		"Finally we approached #feature#",
		"The #trip# had been #effect# so far",
		"The #effect# breakthrough came #time#",
		"To reach #feature# would take many #success#s",
		"We had only #number# days to reach #feature#",
		"We went #direction# to #feature#, not #direction# to #feature#",
		"In #number# days we would reach the #feature#",
		"The #direction# #terrain# looked #anyadjective# here",
		"...Again we paused",
		"We saw a #proximity# #settlement#",
		"We had traveled through the #terrain# #time#"
	],
	"middle": [
		"the effect on #who# was #effect#",
		"we #noted# #omen# and #decision#",
		"#who# #decision#",
		"#who# and #who# #interaction#",
		"#feature# could now be reached",
		"we were the #order# people to travel this #age# path",
		"it seemed like the #order# time",
		"our original #notes# described it better",
		"spirits were as #state# as the local #building#",
		"it would grow harder to track time as #season# set in",
		"we needed to let #who# rest for a while",
		"conversation had #changed# in #season#",
		"the locals spoke of our #anyadjective# #drive#",
		"#who#, #who# and #who# discussed our situation",
		"it now felt like the days had #number# hours in them",
		"we were clearly being followed by #negativeadjective# #animals#",
		"we tried to put #feature# out of our minds",
		"#who# was eager to practice their study #depictions#",
		"the #drive# in our minds waned",
		"the #color# of the light here was #effect#",
		"#who# broke out the #color# #supplies#"
	],
	"end": [
		"this would prove #price#",
		"this marked our #order# #success#",
		"#omen# was what we needed",
		"had this happened sooner, #amount# would have #changed#",
		"we updated our #notes# and #interaction#",
		"henceforth we filled our #notes# with entries #depictions#",
		"but we needed riding #animals# to continue",
		"this would end up digging into our #supplies# supply",
		"here we traded our #supplies# for #notes#",
		"little did we suspect what #who# would do next",
		"we forgot to tell #who# of this",
		"#state# entities we couldn't perceive #interaction#",
		"meanwhile fate stalked us like a #unbiasedadjective# #bodypart#",
		"we were in need of a few #positiveadjective#, #effect# nights",
		"then we made an offering of #supplies# to a #color# #bodypart# shrine",
		"and now #aware# depictions #depictions# beneath our feet",
		"here we would see #amount# of #color# visions",
		"was this what #aware#? #who# had doubts",
		"#who# wished they had #decision# and had not #decision#",
		"much was #noted# in #color# ink the coming weeks"
	],
	"time": [
		"early",
		"later",
		"around the halfway mark",
		"near the start",
		"at the beginning",
		"too soon",
		"far too late",
		"after #number# days",
		"after #number# miles",
		"after #number# weeks",
		"on the #order# leg",
		"before we turned back",
		"before #season#",
		"after #season#",
		"the #order# #season#",
		"between camps",
		"first thing",
		"surprisingly soon",
		"during #season#",
		"after travel had #changed#"
	],
	"trip": [
		"excursion",
		"trip",
		"expedition",
		"trek",
		"travel",
		"journey",
		"voyage",
		"tour",
		"odyssey",
		"hike",
		"tramp",
		"safari",
		"pilgrimage",
		"quest",
		"crusade",
		"jaunt",
		"outing",
		"wandering",
		"story",
		"peregrination"
	],
	"aware": [
		"we caught wind of",
		"the mists parted to reveal",
		"the #terrain# changed in the presence of",
		"we stumbled on",
		"the people of the #settlement# spoke of",
		"voices guided us to",
		"we heard of",
		"we caught a glimpse of",
		"our path pointed towards",
		"we deciphered a way to",
		"word reached us of",
		"the weather uncovered",
		"we breached the veil around",
		"#animals# lead us to",
		"the stars aligned over",
		"our #notes# pinpointed",
		"we found the correct way to",
		"we were in the #negativeadjective# shadow of",
		"#who# tracked down",
		"we could at last perceive"
	],
	"feature": [
		"the #anyadjective# towers",
		"#number# #monument#",
		"the temple of \"#omen#\"",
		"the land of the #material# #terrain#",
		"the #age# ruins",
		"the #state# homelands of #who#",
		"the #anyadjective# #animals# graveyard",
		"the \"#anyadjective# source of all #season#s\"",
		"a #state# vault lined with #notes#",
		"the wreckage of a #price#, #age# ship",
		"the #monument# #depictions#",
		"the \"colossus of #drive#\"",
		"\"the maw of #material# #animals#\"",
		"the #state# ruins that had #amount# inside",
		"#number# #state# standing stones",
		"a long #state# #settlement#",
		"an altar from a #state# #building#",
		"a #monument# as #price# as it was #age#",
		"a #building# acting as a home for #animals#",
		"a #anyadjective# #building#"
	],
	"positiveadjective": [
		"holy",
		"bright",
		"radiant",
		"guiding",
		"wondrous",
		"warm",
		"healing",
		"thrilling",
		"festive",
		"flawless",
		"immaculate",
		"vibrant",
		"verdant",
		"illuminating",
		"useful",
		"empowering",
		"poised",
		"genuine",
		"perfect",
		"regal",
		"golden",
		"pure",
		"amazing",
		"pleasant",
		"sweet",
		"silken",
		"rich",
		"bejeweled",
		"healthy",
		"important",
		"significant",
		"historic",
		"advanced",
		"informative",
		"educational",
		"robust",
		"strong",
		"meritorious",
		"dynamic",
		"powerful",
		"hardy",
		"precious",
		"amusing",
		"whimsical",
		"dear",
		"fine",
		"exquisite",
		"attractive",
		"rewarding",
		"edifying",
		"pleasing",
		"salubrious",
		"beneficial",
		"wholesome",
		"luxurious",
		"grand",
		"astounding",
		"glowing",
		"helpful",
		"thrilling",
		"stirring",
		"exalted"
	],
	"unbiasedadjective": [
		"glinting",
		"colorful",
		"giant",
		"ancient",
		"unknown",
		"bold",
		"high",
		"low",
		"indistinct",
		"smooth",
		"hazy",
		"complex",
		"unknowable",
		"alien",
		"angular",
		"fluid",
		"primitive",
		"humming",
		"vibrating",
		"whispering",
		"elongated",
		"recognizable",
		"thin",
		"alive",
		"impossible",
		"surprising",
		"sharp",
		"blunt",
		"fascinating",
		"ordered",
		"chaotic",
		"indestructible",
		"otherworldly",
		"formless",
		"illusory",
		"stark",
		"bare",
		"basic",
		"cold",
		"hot",
		"wet",
		"dry",
		"unmovable",
		"motionless",
		"reflective",
		"rare",
		"concealed",
		"disguised",
		"secret",
		"delicate",
		"unyielding",
		"puzzling",
		"perplexing",
		"intricate",
		"labyrinthine",
		"knotted",
		"quiet",
		"eerie",
		"curious",
		"spectral",
		"eldritch",
		"intoxicating"
	],
	"negativeadjective": [
		"dark",
		"brooding",
		"ominous",
		"malignant",
		"corrupted",
		"blackened",
		"worn",
		"broken",
		"dire",
		"looming",
		"hateful",
		"lumpen",
		"misshapen",
		"ill wrought",
		"wicked",
		"stained",
		"enraging",
		"poisonous",
		"cancerous",
		"possessed",
		"sinful",
		"punishing",
		"defaced",
		"wretched",
		"frail",
		"twisted",
		"deadly",
		"gory",
		"savage",
		"unpleasant",
		"sickening",
		"gnarled",
		"ruined",
		"toxic",
		"haunted",
		"possessed",
		"pockmarked",
		"troublesome",
		"annoying",
		"irritating",
		"exasperating",
		"irksome",
		"vexatious",
		"inconvenient",
		"bothersome",
		"worrisome",
		"disturbing",
		"upsetting",
		"distressing",
		"perturbing",
		"problematic",
		"thorny",
		"pestilent",
		"smeared",
		"encrusted",
		"burnt",
		"blasted",
		"blackened",
		"unholy",
		"brittle",
		"frightening"
	],
	"who": [
		"the party",
		"our guide",
		"the spy",
		"our ward",
		"the navigator",
		"the child",
		"the #order# guard",
		"our beloved leader",
		"the one that worried us",
		"the captain",
		"the doctor",
		"our adviser",
		"the vazeer",
		"the porter",
		"the savant",
		"our linguist",
		"the student",
		"the collector",
		"the surveyor",
		"the archaeologist",
		"the survivor"
	],
	"effect": [
		"profound",
		"somber",
		"restorative",
		"empowering",
		"thought provoking",
		"disquieting",
		"soporific",
		"harrowing",
		"enlightening",
		"frightening",
		"unexpected",
		"unique",
		"hard to behold",
		"undetectable",
		"salubrious",
		"painful",
		"sudden",
		"otherworldly",
		"singular",
		"lovely",
		"dreadful",
		"nostalgic",
		"warming",
		"cooling",
		"calming",
		"worrying",
		"morale boosting"
	],
	"number": [
		"two",
		"three",
		"four",
		"five",
		"six",
		"seven",
		"eight",
		"nine",
		"ten",
		"many",
		"lots of",
		"scores of",
		"countless",
		"endless",
		"too few",
		"scant",
		"ever amassing",
		"an unknown amount of",
		"six or seven",
		"a dozen",
		"a half dozen",
		"a couple of",
		"about three"
	],
	"depictions": [
		"of snakes",
		"of murderers",
		"of #unbiasedadjective# heads",
		"covered in #negativeadjective# #symbols#",
		"of heroes",
		"of #anyadjective# #animals#",
		"of #effect# beasts",
		"of scenes of #effect# wonders",
		"of hands with #number# digits",
		"of crude versions of #omen#",
		"of the god that #decision#",
		"of #material# eyes that #noted# us",
		"of hooded figures",
		"of diagrams explaining #amount#",
		"of a void",
		"of a great #building# before it fell",
		"of #state# charts",
		"of #price# #material# hordes",
		"of our party",
		"of dead languages"
	],
	"omen": [
		"the omen",
		"the sign",
		"the warning",
		"what we had been told",
		"the information",
		"the vision",
		"the signal",
		"the revelation",
		"the augury",
		"the indication",
		"what we gleaned",
		"what the locals would whisper",
		"the clue",
		"the validation",
		"the answered prayer",
		"what was witnessed",
		"the sight",
		"the occurrence",
		"the happenstance",
		"the fortune"
	],
	"noted": [
		"ignored",
		"noted",
		"felt",
		"memorized",
		"mulled over",
		"recorded",
		"registered",
		"outlined",
		"cataloged",
		"traced",
		"tracked",
		"deciphered",
		"decrypted",
		"itemized",
		"dissected",
		"inventoried",
		"documented",
		"tabulated",
		"identified",
		"named"
	],
	"symbols": [
		"runes",
		"geometric shapes",
		"insectile pictographs",
		"#unbiasedadjective# hand-prints",
		"#positiveadjective# drawings",
		"#unbiasedadjective# scrawls",
		"#number# #color# spirals",
		"#unbiasedadjective# scripts",
		"#color# texts",
		"#negativeadjective# lines",
		"tally marks",
		"#anyadjective# calculations",
		"angles and co-ordinates",
		"tidal charts",
		"measures",
		"shapes like claws and beaks",
		"#negativeadjective# shadows",
		"musical notations",
		"architectural plans",
		"star charts"
	],
	"material": [
		"stone",
		"basalt",
		"glass",
		"rusted",
		"crystal",
		"oozing",
		"ruby",
		"emerald",
		"sapphire",
		"blood",
		"obsidian",
		"wooden",
		"clay",
		"earthen",
		"bone",
		"ceramic",
		"marble",
		"granite",
		"limestone",
		"slate",
		"flesh-like"
	],
	"terrain": [
		"air",
		"grass",
		"trees",
		"scenery",
		"rivers",
		"mountains",
		"volcanic planes",
		"planes",
		"deserts",
		"lakes",
		"streams",
		"hills",
		"outcroppings",
		"thickets",
		"clearings",
		"gardens",
		"mists",
		"swamps",
		"hives",
		"warrens"
	],
	"price": [
		"costly",
		"invaluable",
		"priceless",
		"worthless",
		"expensive",
		"detrimental",
		"dangerous",
		"rewarding",
		"vexing",
		"valuable",
		"sumptuous",
		"exquisite",
		"rare",
		"uncommon",
		"unlikely",
		"singular",
		"grand",
		"rich",
		"opulent",
		"magnificent"
	],
	"interaction": [
		"locked eyes",
		"exchanged insults",
		"shared a laugh",
		"chanted in unison",
		"came to an agreement",
		"shared assurances",
		"changed clothes",
		"organized shifts",
		"made a toast",
		"bargained and wagered",
		"aided one another",
		"changed positions",
		"mirrored one another",
		"picked partners",
		"offered a truce",
		"spoke softly",
		"shared theories",
		"swapped places",
		"exchanged gear",
		"parted"
	],
	"amount": [
		"something",
		"little",
		"much",
		"nothing",
		"everything",
		"some vital things",
		"a significant factor",
		"distinct parts",
		"individual chunks",
		"fragments",
		"bits",
		"all that could be seen",
		"a handful of elements",
		"components",
		"chapters",
		"passages",
		"segments",
		"percentages",
		"scraps",
		"shares"
	],
	"success": [
		"mistake",
		"triumph",
		"small victory",
		"milestone",
		"goal",
		"setback",
		"win",
		"achievement",
		"delight",
		"loss",
		"failure",
		"fault",
		"miscalculation",
		"slip",
		"blunder",
		"fluke",
		"blessing",
		"lucky break",
		"unlucky break",
		"accomplishment"
	],
	"order": [
		"first",
		"last",
		"next",
		"second",
		"final",
		"third",
		"fourth",
		"fifth",
		"penultimate",
		"earliest",
		"latest",
		"sixth",
		"middlemost",
		"foremost",
		"seventh",
		"previous",
		"very next",
		"second to last",
		"eighth",
		"ninth",
		"tenth",
		"out of order"
	],
	"settlement": [
		"village",
		"settlement",
		"tribe",
		"town",
		"camp",
		"caravan",
		"clan",
		"encampment",
		"gang",
		"horde",
		"hamlet",
		"settlement",
		"thorp",
		"colony",
		"pueblo",
		"outpost",
		"farm",
		"bivouac",
		"cabal",
		"shire"
	],
	"proximity": [
		"nearest",
		"distant",
		"nearby",
		"remote",
		"far away",
		"approaching",
		"closest",
		"closest apparent",
		"immediate",
		"closer",
		"lowest",
		"highest",
		"lower",
		"higher",
		"most accessible",
		"near inaccessible",
		"convenient",
		"inconvenient",
		"adjacent",
		"looming"
	],
	"notes": [
		"maps",
		"notes",
		"scrolls",
		"records",
		"ledgers",
		"papers",
		"research",
		"books",
		"notations",
		"inscriptions",
		"entries",
		"logs",
		"incunabula",
		"booklets",
		"guides",
		"dictionaries",
		"writings",
		"stories",
		"works",
		"tomes",
		"texts"
	],
	"age": [
		"ancient",
		"timeless",
		"recent",
		"forgotten",
		"prehistoric",
		"age-old",
		"antiquated",
		"archaic",
		"old-fashioned",
		"antediluvian",
		"timeworn",
		"aged",
		"primitive",
		"decrepit",
		"aged",
		"historic",
		"atavistic",
		"primeval",
		"primordial",
		"out of date"
	],
	"drive": [
		"obsession",
		"plans",
		"will",
		"dream",
		"vengeance",
		"scheme",
		"capitalism",
		"morality",
		"sense of adventure",
		"wanderlust",
		"certainty",
		"conviction",
		"fears",
		"enthusiasm",
		"pride",
		"energy",
		"hunger",
		"recklessness",
		"foolishness",
		"leadership",
		"envy",
		"madness",
		"harmony",
		"honor",
		"funds",
		"theories",
		"reason",
		"stories",
		"threats",
		"hate",
		"love",
		"friendship",
		"pride",
		"guilt",
		"loyalty",
		"independence",
		"power",
		"ambition",
		"blindness",
		"rivalry",
		"grief",
		"betrayal",
		"goals",
		"nightmare",
		"memory",
		"example",
		"destiny",
		"delusion",
		"drive",
		"promise",
		"momentum",
		"tales",
		"curse",
		"blessings",
		"hope",
		"plots",
		"riddle",
		"compassion",
		"conspiracy",
		"loss",
		"control"
	],
	"changed": [
		"changed",
		"been saved",
		"turned against us",
		"gotten worse",
		"been different",
		"been easier",
		"gotten easier",
		"eased",
		"become taxing",
		"gotten better",
		"took a toll",
		"required more time",
		"felt worse",
		"felt better",
		"gone our way",
		"altered",
		"gone to plan",
		"been as we hoped",
		"turned on us",
		"failed us"
	],
	"season": [
		"summer",
		"winter",
		"autumn",
		"fall",
		"spring",
		"the monsoon",
		"the drought",
		"current season",
		"the misty streak",
		"the rainy season",
		"the windy season",
		"the dry spell",
		"the dark time",
		"equinox",
		"the eclipse",
		"blizzard season",
		"the lean time",
		"harvest",
		"the emergence season",
		"the hottest season"
	],
	"animals": [
		"animals",
		"wild cats",
		"birds",
		"lizards",
		"insects",
		"amphibians",
		"apes",
		"boars",
		"bears",
		"fish",
		"reptiles",
		"worms",
		"gulls",
		"horses",
		"cattle",
		"nocturnal creatures",
		"arboreal animals",
		"sea beasts",
		"ungulates",
		"pack animals",
		"howling animals",
		"sloths",
		"moths",
		"toads",
		"frogs",
		"wasps",
		"hounds",
		"bats",
		"salamanders",
		"crabs",
		"spiders",
		"scorpians",
		"starfish",
		"beetles",
		"deer",
		"turtles",
		"moles",
		"snakes",
		"vipers",
		"buffalo",
		"raptors",
		"eagles",
		"foxes",
		"jackals",
		"crows",
		"sharks",
		"tigers",
		"scuttlers",
		"hookbeasts",
		"flenseworms",
		"marrowvores",
		"guiltspinners",
		"pyrerunners"
	],
	"state": [
		"broken",
		"shattered",
		"dusty",
		"fallen",
		"overgrown",
		"gutted",
		"eroded",
		"abandoned",
		"cyclopean",
		"ruined",
		"rusted",
		"neglected",
		"forgotten",
		"encrusted",
		"barnacled",
		"barren",
		"engraved",
		"worn",
		"polished",
		"cobwebbed",
		"vine covered",
		"burnt",
		"slimy",
		"grimy",
		"obscured"
	],
	"color": [
		"black",
		"red",
		"white",
		"umber",
		"deep blue",
		"colorless",
		"iridescent",
		"glossy",
		"gilt",
		"rose",
		"oxidized",
		"verdigris-green",
		"blood-red",
		"ash-white",
		"pallid",
		"faded",
		"faint",
		"luminescent green",
		"luminescent blue",
		"gold",
		"copper",
		"bronze",
		"brass"
	],
	"direction": [
		"north",
		"south",
		"east",
		"west",
		"upwards",
		"downwards",
		"left",
		"right",
		"clockwise",
		"counter-clockwise",
		"inland",
		"outward",
		"north-east",
		"north-west",
		"south-east",
		"south-west",
		"south-south-east",
		"south-south-west",
		"north-north-east",
		"north-north-west"
	],
	"supplies": [
		"ration",
		"food",
		"water",
		"cheese",
		"wine",
		"rum",
		"torch",
		"oil",
		"holy water",
		"medicine",
		"clean clothes",
		"cod-liver oil",
		"protective amulet",
		"bandage",
		"chocolate",
		"ointment",
		"gold",
		"trinket",
		"ammunition",
		"good humor"
	],
	"building": [
		"hall",
		"church",
		"temple",
		"coliseum",
		"building",
		"hut",
		"basilica",
		"monastery",
		"shrine",
		"barn",
		"stable",
		"well house",
		"cellar",
		"archive",
		"library",
		"school",
		"prison",
		"foundry",
		"mill",
		"barracks",
		"citadel",
		"castle",
		"boathouse",
		"lighthouse"
	],
	"monument": [
		"statues",
		"monoliths",
		"#material# dwellings",
		"#unbiasedadjective# ruins",
		"carvings",
		"#price# #material# obelisks",
		"pyramids",
		"#anyadjective# cubes",
		"#color# spheres",
		"steps to a #price# throne",
		"relics",
		"walls",
		"crypts",
		"sepulchers",
		"graves",
		"tombs",
		"plinths",
		"roads",
		"menhirs",
		"arches",
		"barrows",
		"wells",
		"ramparts",
		"stairs",
		"columns",
		"amphitheaters",
		"coliseums",
		"courts",
		"roads",
		"gates",
		"doors",
		"paths",
		"statues",
		"thrones",
		"aqueducts",
		"gardens",
		"graveyards",
		"trenches"
	],
	"bodypart": [
		"maw",
		"mouth",
		"teeth",
		"beak",
		"brow",
		"spine",
		"ribcage",
		"bone",
		"eye",
		"tounge",
		"tail",
		"claw",
		"spine",
		"spike",
		"scale",
		"fin",
		"sting",
		"wing",
		"pincer",
		"spinerete"
	],
	"decision": [
		"pushed on",
		"muttered quietly",
		"didn't look back",
		"took stock of our remaining #supplies#",
		"broke camp",
		"also made plans",
		"made calculations",
		"followed #who#",
		"raised fees",
		"asked for assistance",
		"ranted and raved",
		"took in the sights",
		"offered to lead",
		"confirmed #omen#",
		"confessed some relief",
		"showed no eagerness to continue",
		"flipped a coin",
		"looked upset",
		"tried not to look surprised",
		"started to think of other things"
	]
});
 
grammar.addModifiers(tracery.baseEngModifiers); 
 

window.document.getElementById('sentence').innerHTML = grammar.flatten('#origin#');